<?php
/**
 * Effy Freshdesk extension
 *
 * @category    Effy_Freshdesk
 * @package     Effy_Freshdesk
 * @copyright   Copyright (c) 2014 Effy. (http://www.effy.com)
 * @license     http://www.effy.com/disclaimer.html
 */

/**
 * @see Effy_Freshdesk_Block_Field_Paragraph
 *
 * @var Effy_Freshdesk_Block_Field_Paragraph $this
 */

echo $this->getEditor()->toHtml();
/*?>
<textarea id="<?php echo $this->getFieldId(); ?>" name="<?php echo $this->getFieldName(); ?>"
          class="<?php echo $this->getFieldClass(); ?>" rows="2" cols="15"></textarea>
<?php */